import express from "express";
import { getAllForecasts } from "../services/forecastService.js";

const router = express.Router();

/*
============================================================
GET ALL FORECASTS
============================================================

Endpoint:

GET /api/forecast

Returns the forecast output generated by:
- XGBoost
- LSTM
- Prophet

The actual model files are handled by forecastService.js.
The frontend should consume this API instead of accessing
model_outputs directly.
============================================================
*/

router.get("/", (req, res) => {
  try {
    console.log("======================================");
    console.log(" Loading forecast outputs");
    console.log("======================================");

    const forecasts = getAllForecasts();

    return res.status(200).json({
      success: true,
      data: forecasts
    });

  } catch (error) {

    console.error("======================================");
    console.error(" Forecast API error");
    console.error("======================================");
    console.error(error);

    return res.status(500).json({
      success: false,
      message: "Unable to load forecast results.",
      error: error.message
    });
  }
});


/*
============================================================
OPTIONAL MODEL-SPECIFIC ENDPOINT
============================================================

Examples:

GET /api/forecast/xgboost
GET /api/forecast/lstm
GET /api/forecast/prophet

This currently gets the complete forecast object and extracts
the requested model.

This makes the frontend easier to use.
============================================================
*/

router.get("/:model", (req, res) => {

  try {

    const requestedModel =
      req.params.model.toLowerCase();

    const forecasts = getAllForecasts();

    let modelData = null;

    if (requestedModel === "xgboost") {

      modelData =
        forecasts.xgboost ??
        forecasts.XGBoost;

    } else if (requestedModel === "lstm") {

      modelData =
        forecasts.lstm ??
        forecasts.LSTM;

    } else if (requestedModel === "prophet") {

      modelData =
        forecasts.prophet ??
        forecasts.Prophet;

    } else {

      return res.status(400).json({
        success: false,
        message:
          "Invalid model. Use xgboost, lstm, or prophet."
      });
    }

    if (!modelData) {

      return res.status(404).json({
        success: false,
        message:
          `Forecast output for ${requestedModel} was not found.`
      });
    }

    return res.status(200).json({
      success: true,
      model: requestedModel,
      data: modelData
    });

  } catch (error) {

    console.error(
      "Model forecast API error:",
      error
    );

    return res.status(500).json({
      success: false,
      message:
        "Unable to load model forecast.",
      error: error.message
    });
  }
});


export default router;